export const LECTURE_LIST_REQUEST = "LECTURE_LIST_REQUEST";
export const LECTURE_LIST_SUCCESS = "LECTURE_LIST_SUCCESS";
export const LECTURE_LIST_FAIL = "LECTURE_LIST_FAIL";

export const LECTURE_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const LECTURE_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const LECTURE_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const LECTURE_DELETE_REQUEST = "LECTURE_DELETE_REQUEST";
export const LECTURE_DELETE_SUCCESS = "LECTURE_DELETE_SUCCESS";
export const LECTURE_DELETE_FAIL = "LECTURE_DELETE_FAIL";
